DAC6-3089: Play 3.0 update
hmrc/country-by-country-reporting pull request #64
Opened 2024-06-04 09:14 UTC by koladeadewuyi

2024-06-04 10:27 UTC, chriswaugh requested changes
The integration test files need moving into a `test` sub folder otherwise they won't be picked up when we run `sbt it/test`.

So instead of the files being in `/it` they need to be in `/it/test`

2024-06-04 10:52 UTC, chriswaugh approved these changes

2024-06-05 11:03 UTC, C-Thomp submitted a review, later dismissed
Appr. formatting additions

2024-06-05 11:48 UTC, C-Thomp approved these changes

2024-06-06 08:31 UTC, merged