DAC6-2746: Allow large file uploads via SDES
hmrc/country-by-country-reporting pull request #65
Opened 2024-07-29 08:47 UTC by koladeadewuyi

2024-07-30 01:25 UTC, oarshad requested changes
Looks good overall - some minor suggestions

2024-07-30 01:25 UTC, oarshad commented on app/services/submission/SDESService.scala
> +  def createFileNotificationRequest(
can be private

2024-07-30 01:25 UTC, oarshad commented on it/test/wiremock/WireMockHelper.scala
> +        val (key, value) = header
can be inlined above
```
headers.foldLeft(builder) { case (builder, (key, value)) =>
```

2024-07-30 01:25 UTC, oarshad commented on test/controllers/submission/SubmissionControllerSpec.scala
> +      forAll(arbitrary[SubmissionDetails]) { submissionDetails =>
```
forAll { submissionDetails: SubmissionDetails =>
```
it should pickup the implicit

2024-07-30 01:25 UTC, oarshad commented on test/controllers/submission/SubmissionControllerSpec.scala
> +      forAll(arbitrary[SubmissionDetails]) { submissionDetails =>
same as above - and also every where if we passing implicit arbitraries within `forAll`

2024-07-30 01:25 UTC, oarshad commented on test/services/submission/SDESFileMetadataServiceSpec.scala
> +        ) { (responseDetail, conversationId, fileName) =>
```
      implicit val nonEmptyString: Arbitrary[String] = Arbitrary(Gen.alphaNumStr.suchThat(_.nonEmpty))

      "must compile metadata for an organisation" in {
        forAll{ (responseDetail: ResponseDetail, conversationId: ConversationId, fileName: String) =>
        ```

2024-07-30 01:25 UTC, oarshad commented on test/services/submission/SDESServiceSpec.scala
> +        forAll(arbitrary[ResponseDetail], arbitrary[SubmissionDetails]) { (responseDetail, submissionDetails) =>
same as above

2024-07-30 15:28 UTC, koladeadewuyi commented on app/models/xml/XmlHandler.scala
> +    }.load(new URL(url))
We're using java 11 which does not include `URI`.
It is now wrapped in a `Try` to handle any exception which may be thrown.

2024-07-31 07:06 UTC, oarshad approved these changes

2024-08-01 10:33 UTC, merged